stages:
  - build
  #- test

variables:
  SOLUTION: "Warehouse_Simulation.sln"


before_script:
  - export GIT_TERMINAL_PROMPT=0
  - export GIT_ASKPASS=""
  #- apt-get update -qy
  - apt-get install -y --no-install-recommends nuget
  - apt-get install -y dotnet-sdk-8.0
  - export PATH=$PATH:/usr/share/dotnet
  - nuget restore $SOLUTION

build:
  stage: build
  script:
    - find / -name msbuild
    - /usr/share/dotnet/msbuild /p:Configuration=Release $SOLUTION

#test:
  #stage: test
  #script:
    #- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

