stages:
  - build
  #- test

variables:
  SOLUTION: "Warehouse_Simulation.sln"
  TIMEZONE: "CET"

before_script:
  - apt-get update -qy
  - apt-get install -y nuget
  - nuget restore $SOLUTION

build:
  stage: build
  script:
    - export TZ=$TIMEZONE
    - msbuild /p:Configuration=Release $SOLUTION

#test:
  #stage: test
  #script:
    #- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

