image: mcr.microsoft.com/dotnet/sdk:8.0


stages:
  - build
  - test
  - deploy

variables:
  SOLUTION: "Warehouse_Simulation.sln"

before_script:
  - 'echo | dotnet --version' # must be v 2.2.300 or later for reporter tool to work
  - apt-get update -qq

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build
    - echo "Build succes"
  
release:
  stage: build
  script:
    - dotnet publish -c Release -r win10-x64
    - echo "Publish succes"
    - pwd
    - ls
    - cd Warehouse_Simulation_WPF
    - ls
    - cd bin
    - ls
    - cd Release
    - ls
    - cd net8.0-windows
    - ls
  artifacts:
    paths:
      - Warehouse_Simulation_WPF/bin/Release/net8.0-windows/publish
    expire_in: 1 week


test:
  stage: test
  script:
    - dotnet test
    - echo "Test succes"