image: mcr.microsoft.com/dotnet/sdk:8.0


stages:
  - build
  - test
  - deploy

variables:
  SOLUTION: "Warehouse_Simulation.sln"

before_script:
  - 'echo | dotnet --version'
  - apt-get update -qq
  - apt-get install bc -y
  - 'export DOTNET_CLI_TELEMETRY_OPTOUT=1'
  - 'export PATH=$PATH:$HOME/.dotnet/tools'
  - 'dotnet tool install dotnet-reportgenerator-globaltool --global || echo "DRG already installed."'

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build
    - echo "Build succes"


test:
  stage: test
  script:
    - 'dotnet test *.sln 
        --collect:"XPlat Code Coverage"
        --results-directory cobertura'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura/*/coverage.cobertura.xml



release:
  stage: deploy
  only: 
    - master
  script:
    - pwd
    - ls -a
    - dotnet publish ./Warehouse_Simulation.sln -o ./Release --runtime win-x64 --configuration Release --sc true -p:PublishProfile=PublishSingleFile -p:UseAppHost=true
    - echo "Publish succes"
    - ls
  artifacts:
    paths:
      - ./Release