image: mcr.microsoft.com/dotnet/sdk:8.0


stages:
  - build
  - test
  - deploy

variables:
  SOLUTION: "Warehouse_Simulation.sln"

before_script:
  - 'echo | dotnet --version' # must be v 2.2.300 or later for reporter tool to work
  - apt-get update -qq

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build
    - echo "Build succes"
  
release:
  stage: build
  script:
    - dotnet publish --output "./Release" --runtime win-x64 --configuration Release -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
    - echo "Publish succes"
    - pwd
    - ls
    - cd Release
    - ls
  artifacts:
    paths:
      - Release
    expire_in: 1 week


test:
  stage: test
  script:
    - dotnet test
    - echo "Test succes"